version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1504869732
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-7835
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: enable
      autoplay: enable
      imageOverlay: disable
      items:
        -
          image: 'gantry-media://2017/08/DSC_0124-1.jpg'
          title: 'FreeSpirit ESU'
          desc: 'Explorer Scouts in South Wales'
          link: /
          linktext: 'Start Here'
          buttonclass: button-outline
          name: 'Sailing Pic'
        -
          image: 'gantry-media://2017/08/the_burn_run.jpg'
          title: 'FreeSpirit ESU'
          desc: 'Explorer Scouts in South Wales'
          link: /
          linktext: 'Start Here'
          buttonclass: button-outline
          name: 'Burn Run Pic'
        -
          image: 'gantry-media://2017/08/an_extremely_tiring_cobbler.jpg'
          title: 'FreeSpirit ESU'
          desc: 'Explorer Scouts in South Wales'
          link: /
          linktext: 'Start Here'
          buttonclass: button-outline
          name: 'Cobbler Pic'
